### ISSUE TITLE
OpenControl happy hour, 7/31/17

### ISSUE THREAD

**Issue by afeld** [opencontrol/discuss#29]
I’m going to be in DC for Project Boise (#28) meetings - let’s do an OpenControl get-together! Monday 7/31 at Elephant & Castle at 900 19th Street at 5:30pm. All are welcome.

https://www.yelp.com/biz/elephant-and-castle-washington-3

**Comment by shawndwells** [comment]
Added to my calendar. Definitely see you there.

**Comment by afeld** [comment]
Reminder this is today!

**Comment by afeld** [comment]
Thanks everyone for coming! Will plan another next time I'm in town (but don't wait for me if someone else wants to put one together).
