### ISSUE TITLE
What is LATO?

### ISSUE THREAD

**Issue by pburkholder** [opencontrol/discuss#3]
https://github.com/18F/GSA-Certifications/blob/master/LATO.yaml 

I've seen this referenced a few places with no context. What is it? The repo doesn't provide any references or information (I can open an issue there if necessary).

**Comment by jcscottiii** [comment]
LATO stands for lightweight authority to operate. In particular, GSA can offer a LATO to an application / platform, given that the 24 specified controls are implemented. The LATO is time-boxed (although, you can renew for another LATO period)

More reading on it:
https://gsablogs.gsa.gov/innovation/2014/12/10/it-security-security-in-an-agile-development-cloud-world-by-kurt-garbars/
https://pages.18f.gov/before-you-ship/ato/types/
