### ISSUE TITLE
"official" content install paths?

### ISSUE THREAD

**Issue by shawndwells** [opencontrol/discuss#30]
In preparing to package OpenControl for Enterprise Linux, I need to set an installation path.

Not sure OpenControl content has been packaged for the enterprise yet, so not sure if install paths have been determined.

How does ``/usr/share/opencontrol/${VENDOR}`` sound?

e.g. 
/usr/share/opencontrol/RedHat/{product1 product2 productX}
/usr/share/opencontrol/Docker/{product1 productX}

**Comment by johnmod3** [comment]
Not sure, this seems to be one of the bigger issues

**Comment by shawndwells** [comment]
Went with ``/usr/share/opencontrol/${VENDOR}`` for now. Open to other suggestions!

**Comment by shawndwells** [comment]
ref: https://github.com/opencontrol/RedHat/blob/master/opencontrol-redhat.spec
