### ISSUE TITLE
remove stale opencontrol/PCI-DSS-Standards repo?

### ISSUE THREAD

**Issue by shawndwells** [opencontrol/discuss#45]
The https://github.com/opencontrol/PCI-DSS-Standards hasn't been touched for a few years, and the PCI-DSS content was incorporated into https://github.com/opencontrol/standards.

As a little spring cleaning, should the https://github.com/opencontrol/PCI-DSS-Standards repo be removed? Would it make sense to create an updated README for a little while?

(IMHO an updated readme is not needed, since the opencontrol/standards project has included PCI-DSS for at least 6mo)

**Comment by shawndwells** [comment]
Bump. Repo has been deprecated since June.  Time to remove it. 

@gregelin @joshuamckenty , I don't have permissions to drop the repo. Could one of you handle that?

**Comment by shawndwells** [comment]
@joshuamckenty bump on this one too

**Comment by afeld** [comment]
It's archived, and I think it's fine to leave it that way. Thanks!
