### ISSUE TITLE
remove stale cf-compliance-DEPRECATED repo?

### ISSUE THREAD

**Issue by shawndwells** [opencontrol/discuss#46]
https://github.com/opencontrol/cf-compliance-DEPRECATED was deprecated three years ago. Time to remove it?

**Comment by joshuamckenty** [comment]
Totally makes sense to me. Do you think there's a broader set of deprecated repos we should archive?

**Comment by shawndwells** [comment]
On 6/4/18 1:31 PM, Joshua McKenty wrote:
> Totally makes sense to me. Do you think there's a broader set of 
> deprecated repos we should archive?

Definitely. Didn't want to spam "deprecate this repo" tickets before 
seeing if there was an appetite to do that. Will keep going through the 
repos over the next few days.

**Comment by shawndwells** [comment]
re-opening ticket. Old repo still exists.

**Comment by joshuamckenty** [comment]
Ah... I had "archived" it - do you think there's value to removing it as well? (It's read-only now and can't be starred).

**Comment by shawndwells** [comment]
Yes, for general housekeeping. Also:

- https://github.com/opencontrol/cf-compliance-DEPRECATED was a fork of https://github.com/cloudfoundry-community-attic/compliance-DEPRECATED. There's no loss of content by removing the OpenControl fork;

- https://github.com/opencontrol/cf-compliance lives on
