### ISSUE TITLE
remove stale NIST-800-53-Standards repo?

### ISSUE THREAD

**Issue by shawndwells** [opencontrol/discuss#47]
Has been incorporated into https://github.com/opencontrol/standards for over a year

**Comment by joshuamckenty** [comment]
It occurs to me that we might have users with old CI pipelines still pointed at these repos... going to rename them for a week or two first and see if anyone yells...

**Comment by shawndwells** [comment]
https://github.com/opencontrol/NIST-800-53-Standards-DEPRECATED has been depricated since June.

Any objections to removing the repo?

+cc @gregelin (saw you snuck some commits into the repo last week without using PRs... tisk tisk)

**Comment by shawndwells** [comment]
@joshuamckenty (or @gregelin), I don't have privs to drop the repo. Will require some action on your part :)

Not something to interrupt holiday vacations over. This can wait until whenever normal work returns for y'all.

**Comment by afeld** [comment]
Archived the repository, which should be a clear enough sign. Thanks all!

**Comment by shawndwells** [comment]
On 1/1/19 11:56 PM, Aidan Feldman wrote:
> Archived the repository, which should be a clear enough sign. Thanks all!

Could this repo be removed entirely verse deprecated?

There's all these old repos left around in the OpenControl org, giving 
the impression everything is either deprecated, archived, or abandoned 
years ago.

Desperately needs to be cleaned up -- old repos should be removed 
entirely, not more abandoned or "archived" things created.

**Comment by shawndwells** [comment]
Repo was stale for many years, code moved into https://github.com/opencontrol/standards, and old repo was marked deprecated since January. Removing old repo and resolving the ticket.
