### ISSUE TITLE
Compoents from git?

### ISSUE THREAD

**Issue by git-ingham** [opencontrol/discuss#52]
I want to set up in opencontrol.yaml that the components are obtainable from git.  So many other parts support checking out from git, but I cannot find any examples or documentation about keeping the components in git.

Obviously, I can use git behind-the-scenes, but I was hoping to just specify the repo in opencontrol.yaml and be done.

Can this be done?

Thanks

**Comment by shawndwells** [comment]
On 12/6/18 1:53 PM, Kenneth Ingham wrote:
>
> I want to set up in opencontrol.yaml that the components are 
> obtainable from git. So many other parts support checking out from 
> git, but I cannot find any examples or documentation about keeping the 
> components in git.
>
> Obviously, I can use git behind-the-scenes, but I was hoping to just 
> specify the repo in opencontrol.yaml and be done.
>
> Can this be done?
>
Absolutely! :)

Here's the opencontrol.yaml [0] we use to power Red Hat's ATO Pathways [1].


[0] https://github.com/RedHatGov/ato-pathways/blob/master/opencontrol.yaml
[1] http://atopathways.redhatgov.io/product-documents/

**Comment by git-ingham** [comment]
Latest version (from earlier today) seems to work OK.  Thanks.

**Comment by git-ingham** [comment]
Latest version (from earlier today) seems to work OK.  Thanks.
