### ISSUE TITLE
remove stale https://github.com/opencontrol/compliance-masonry-go repo

### ISSUE THREAD

**Issue by shawndwells** [opencontrol/discuss#53]
Has been marked deprecated for years. Moved to https://github.com/opencontrol/compliance-masonry.

@joshuamckenty or @gregelin can you remove the old repo?

(or give @redhatrises and myself perms to start cleaning these out?)

**Comment by shawndwells** [comment]
@afeld Would you mind giving @redhatrises (Gale Alford) and I org permissions? We can't move the project forward without them at this point.

**Comment by anweiss** [comment]
@shawndwells done

**Comment by shawndwells** [comment]
Thank you, @anweiss! Removed the old repo, resolving this ticket.
