### ISSUE TITLE
remove sctools repo

### ISSUE THREAD

**Issue by shawndwells** [opencontrol/discuss#55]
Let's remove abandoned https://github.com/opencontrol/sctools repo.

It's a fork of https://github.com/usnistgov/sctools anyway -- doesn't seem necessary to keep in OpenControl repos.

+cc @joshuamckenty and @gregelin as they've org permissions for this

**Comment by afeld** [comment]
@shawndwells Do you feel strongly about the repositories being deleted, as opposed to just archived?

**Comment by joshuamckenty** [comment]
Deleted this one. I feel like bare forks (with no unique commits) are safe to delete; want to be more thoughtful about the other ones.
